name: Build Package and Pack Nuget

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: dotnet restore ./Razor-UTC.sln
      
    - name: Build Project
      run: dotnet build --configuration Release

    - name: Pack NuGet Package
      run: dotnet pack --configuration Release --output ./artifacts
